### ISSUE TITLE
throws integer error when installed and using python2.7

### ISSUE THREAD

**Issue by bnvk** [juga0/dhcpcanon#21]
Traceback (most recent call last):
  File "/usr/local/sbin/dhcpcanon", line 11, in <module>
    load_entry_point('dhcpcanon==0.8.0', 'console_scripts', 'dhcpcanon')()
  File "/usr/local/lib/python2.7/dist-packages/dhcpcanon-0.8.0-py2.7.egg/dhcpcanon/dhcpcanon.py", line 89, in main
    dhcpcap.run()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/automaton.py", line 899, in run
    six.reraise(c.exc_info[0], c.exc_info[1], c.exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/automaton.py", line 743, in _do_control
    state = next(iterator)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/automaton.py", line 813, in _do_iter
    self._run_condition(timeout_func, *state_output)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/automaton.py", line 694, in _run_condition
    action(self, *state_req.action_args, **state_req.action_kargs)
  File "/usr/local/lib/python2.7/dist-packages/dhcpcanon-0.8.0-py2.7.egg/dhcpcanon/dhcpcapfsm.py", line 646, in action_transmit_discover
    self.send_discover()
  File "/usr/local/lib/python2.7/dist-packages/dhcpcanon-0.8.0-py2.7.egg/dhcpcanon/dhcpcapfsm.py", line 154, in send_discover
    sendp(pkt)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/sendrecv.py", line 304, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/sendrecv.py", line 265, in __gen_send
    s.send(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/arch/linux.py", line 545, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/supersocket.py", line 42, in send
    sx = raw(x)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/compat.py", line 72, in raw
    return x.__bytes__()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 338, in __bytes__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 436, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 421, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 408, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 421, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 408, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 421, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 408, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 421, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 408, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 418, in do_build
    pkt = self.self_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/packet.py", line 399, in self_build
    p = f.addfield(self, p, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/fields.py", line 408, in addfield
    return s + self.i2m(pkt, val)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/layers/dhcp.py", line 269, in i2m
    lval = [f.addfield(pkt,b"",f.any2i(pkt,val)) for val in lval]
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/fields.py", line 732, in addfield
    s = self.field.addfield(pkt, s, v)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.0rc4-py2.7.egg/scapy/fields.py", line 80, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
struct.error: cannot convert argument to integer

**Comment by juga0** [comment]
Thanks @bnvk for reporting this bug.
I'm removing support for python 2,  https://github.com/juga0/dhcpcanon/commit/23cdeeee604f7f848063ea4a2869559e5de0fb22 installs and uses python 3
