### ISSUE TITLE
Exception when running under Fedora Core 26 

### ISSUE THREAD

**Issue by DrWhax** [juga0/dhcpcanon#26]
```
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]: ......
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]: Sent 1 packets.
Apr 14 12:48:49 dhcpanon python3[3179]: detected unhandled Python exception in '/sbin/dhcpcanon'
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]: Traceback (most recent call last):
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]:   File "/sbin/dhcpcanon", line 11, in <module>
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]:     load_entry_point('dhcpcanon==0.8.5', 'console_scripts', 'dhcpcanon')()
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]:   File "/usr/lib/python3.6/site-packages/dhcpcanon-0.8.5-py3.6.egg/dhcpcanon/dhcpcanon.py", line 89, in main
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]:     dhcpcap.run()
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]:   File "/usr/lib/python3.6/site-packages/scapy_python3-0.23-py3.6.egg/scapy/automaton.py", line 715, in run
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]:     raise c.exc_info[0](c.exc_info[1])
Apr 14 12:48:49 dhcpanon dhcpcanon[3179]: ValueError: invalid literal for int() with base 10: ''
Apr 14 12:48:49 dhcpanon systemd[1]: dhcpcanon.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 12:48:49 dhcpanon audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=dhcpcanon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 14 12:48:49 dhcpanon systemd[1]: dhcpcanon.service: Unit entered failed state.
Apr 14 12:48:49 dhcpanon systemd[1]: dhcpcanon.service: Failed with result 'exit-code'.
Apr 14 12:48:50 dhcpanon abrt-notification[3512]: Process 3179 (dhcpcanon) of user 988 encountered an uncaught ValueError exception
-- Subject: ABRT has detected an uncaught ValueError exception in dhcpcanon
-- Defined-By: ABRT
-- Support: https://bugzilla.redhat.com/
-- Documentation: man:abrt(1)
-- PROBLEM_REPORT
-- Use the abrt command-line tool for further analysis or to report
-- the problem to the appropriate support site.
```

I can't reproduce it yet.

**Comment by DrWhax** [comment]
```
2018-04-14 13:06:16 DEBUG timers.py:74 - gen_timeout_resend - next timeout resending will happen on 18-04-14 13:07:20
2018-04-14 13:06:16 DEBUG dhcpcapfsm.py:146 - set_timeout - Set state SELECTING, function timeout_selecting, to timeout 64.40075963077705
2018-04-14 13:06:16 DEBUG dhcpcapfsm.py:411 - ERROR - In state: ERROR
```

retrieved when running dhcpcanon with ```--verbose```.
